### ISSUE TITLE
ENH: close pop up window with a hotkey.

### ISSUE THREAD

**Issue by TKosir** [ladisk/LadiskDAQ#15]

**Comment by klemengit** [comment]
Done with commit deacdf350e1675ade8f6f71a9faceecd234c4f6f.

Current hotkeys:
- `s`: start acquisition.
- `q`: if acquisition not stopped, stop. If acquisition stopped, close app.
- `f`: toggle freeze plot.
- `F11`: toggle full screen.
- `l` (lower-case L): toggle legend.
