### ISSUE TITLE
Freeze plot with hotkey "f" not implemented

### ISSUE THREAD

**Issue by TKosir** [ladisk/LadiskDAQ#18]

**Comment by TKosir** [comment]
This should be added as a visualization class hotkey

**Comment by klemengit** [comment]
Added hotkeys:
- f (toggle freeze)
- CTRL + f (toggle full-screen)
- CTRL + l (toggle legend)

Implemented in commit 9bbe408669ef6d69ab37507b390e11100a46316f.
