### ISSUE TITLE
ENH: use time module in acquisition and core module where sampling freq is not available

### ISSUE THREAD

**Issue by klemengit** [ladisk/LadiskDAQ#8]
if sample rate is present in acq., use sample rate for the plotting.
if the sample rate is not present, use time module (time.time).
if channels from multiple different acquisitions are plotted in the same subplot, use time module for time axis.

(for acquisition: if sample rate variable is not present, add channel to the end which represents the time vector.)

**Comment by TKosir** [comment]
Implemented in the new version.
